### PR TITLE
Add next start date/time on the HA component

### PR DESCRIPTION
**Pull request by andyb2000**
Added next start time to the Home Assistant component.

image

### CODE REVIEW

**Comment by andyb2000** [comment]
Apologies, found a bug whereby when mower is running it does not return a next_start_time which caused a crash. Added an exception in for this.

**Comment by andyb2000** [comment]
Added the other statistics:

image

**Comment by andyb2000** [comment]
Split into categories:
image

**Comment by peternijssen** [comment]
Perhaps interesting to see how they added multiple sensors in Roborock. Rather then creating a new class every time, they just created a single class. Not sure if that's possible here, but that would save a lot of code and makes adding more sensors easy; https://github.com/home-assistant/core/blob/dev/homeassistant/components/roborock/sensor.py

**Comment by andyb2000** [comment]
> Perhaps interesting to see how they added multiple sensors in Roborock. Rather then creating a new class every time, they just created a single class. Not sure if that's possible here, but that would save a lot of code and makes adding more sensors easy; https://github.com/home-assistant/core/blob/dev/homeassistant/components/roborock/sensor.py

Ta, yes good point.
I have done for other components I've implemented, but was just basing this on the original PR to HA for this code.
For now this probably will be cancelled and I'll wait until it gets pushed to HA before updating and sending a further PR.

**Pull request closed without merging**
